### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by duffn** [pasindud/awesome-loopback#11]
I see that the Projects section generally contains projects that specifically mention that they are using LoopBack. Is that intentional for some reason or can we put any projects there that use LoopBack?

I was thinking specifically about [Free Code Camp](https://github.com/FreeCodeCamp/FreeCodeCamp), but I'm sure there many others. They use LoopBack, but don't "advertise" it on the front page of the repo like these other projects do.

**Comment by pasindud** [comment]
Will add it :+1:

**Comment by pasindud** [comment]
Added
